
spring:
  datasource:
    url: jdbc:mysql://101.34.124.113:3306/self01?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true
    username: ${DATABASE_USERNAME:cdd}
    password: ${DATABASE_PASSWORD:Cdd123456@}
    driverClassName: com.mysql.cj.jdbc.Driver

#mp日志打印-形式1：
#mybatis-plus:
# configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mp日志打印-形式2：
logging:
  level:
    com:
      cdd:
        self01:
          repository:
            mapper: debug